spring:
  config:
    import:
      - classpath:properties/live/security.yml
      - classpath:properties/live/database.yml
      - classpath:properties/live/cloud.yml
      - classpath:properties/live/admin.yml
      - classpath:properties/live/app.yml
